name: Trigger Server Update

on:
  push:
    branches:
      - main

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call Deployment Script
        run: |
          curl -L -s -k"http://pdv.institutodoceo.com/upload_version.php?key=UPL-AmorVincitOmnia3*1-DOC&run=${{ github.run_id }}"
